# Generated by Django 4.2.10 on 2024-03-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninthdjango', '0003_alter_video_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='video',
            name='photo_url',
            field=models.URLField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(max_length=100000),
        ),
    ]
