# Generated by Django 4.2.10 on 2024-04-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninthdjango', '0005_thumbnails'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('video_key', models.TextField()),
                ('photo_key', models.TextField()),
            ],
        ),
    ]
