# Generated by Django 4.2.10 on 2024-04-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninthdjango', '0008_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='videometadata',
            name='background_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
